# Generated by DeployCtrl
# Request ID  : 69d88dd57dd9f40a7aff4bb8
# Template    : S3 Bucket
# Team        : Product A
# Requested by: Alice Developer
# Region      : us-east-1

storage_class     = "STANDARD"
estimated_size_gb = 10
versioning        = "Enabled"
encryption        = "AES256"
access_control    = "private"
lifecycle_days    = 0
region            = "us-east-1"
name_prefix       = "deployctrl-product-a-req-0032"
bucket_name       = "deployctrl-product-a-7aff4bb8"
