# Generated by DeployCtrl
# Request ID  : 69d6f464ca602ba9fd977746
# Template    : S3 Bucket
# Team        : Product A
# Requested by: Alice Developer
# Region      : us-east-1

storage_class     = "STANDARD"
estimated_size_gb = 50
versioning        = "Enabled"
encryption        = "AES256"
access_control    = "private"
lifecycle_days    = 3
region            = "us-east-1"
name_prefix       = "deployctrl-product-a"
bucket_name       = "deployctrl-product-a-fd977746"
