# Generated by DeployCtrl
# Request ID  : 69fa8192b125fc216db3901f
# Template    : S3 Bucket
# Team        : Product A
# Requested by: Alice Developer
# Region      : us-east-1

storage_class     = "STANDARD"
estimated_size_gb = 10
versioning        = "Suspended"
encryption        = "AES256"
access_control    = "private"
lifecycle_days    = 0
region            = "us-east-1"
name_prefix       = "deployctrl-product-a-req-0004"
bucket_name       = "deployctrl-product-a-6db3901f"
