# Generated by DeployCtrl
# Request ID  : 69c73ac4e1dedf95b2118fff
# Template    : EC2 Instance
# Team        : Product A
# Requested by: Alice Developer
# Region      : us-east-1

instance_type  = "t3.medium"
disk_type      = "gp3"
disk_size_gb   = 20
os             = "ubuntu-22.04"
inbound_ports  = ["22", "443"]
outbound_ports = ["all"]
region         = "us-east-1"
name_prefix    = "deployctrl-product-a"
