# Generated by DeployCtrl
# Request ID  : 69d9a23f55ec8ac9c7811082
# Template    : S3 Bucket
# Team        : Product A
# Requested by: Alice Developer
# Region      : us-east-1

storage_class     = "STANDARD"
estimated_size_gb = 10
versioning        = "Enabled"
encryption        = "AES256"
access_control    = "private"
lifecycle_days    = 0
region            = "us-east-1"
name_prefix       = "deployctrl-product-a-req-0036"
bucket_name       = "deployctrl-product-a-c7811082"
