# Generated by DeployCtrl
# Request ID  : 69d6f4de5ec48ae184a4e3e8
# Template    : EC2 Instance
# Team        : Governance
# Requested by: Bob Architect
# Region      : ap-southeast-1

instance_type  = "t3.xlarge"
disk_type      = "gp2"
disk_size_gb   = "200"
os             = "windows-2022"
inbound_ports  = ["22", "80", "443"]
outbound_ports = ["all"]
region         = "ap-southeast-1"
name_prefix    = "deployctrl-governance"
