# Generated by DeployCtrl
# Request ID  : 69d83c7c5ec48ae184a4e429
# Template    : EC2 Instance
# Team        : Platform
# Requested by: Admin User
# Region      : us-east-1

instance_type  = "t3.small"
disk_type      = "gp3"
disk_size_gb   = "20"
os             = "amazon-linux-2"
inbound_ports  = ["22", "80", "443"]
outbound_ports = ["all"]
region         = "us-east-1"
name_prefix    = "deployctrl-platform"
