# Generated by DeployCtrl
# Request ID  : 69d70d4c5ec48ae184a4e40d
# Template    : S3 Bucket
# Team        : Platform
# Requested by: Admin User
# Region      : us-east-1

storage_class     = "STANDARD"
estimated_size_gb = 10
versioning        = "Enabled"
encryption        = "AES256"
access_control    = "private"
lifecycle_days    = 0
region            = "us-east-1"
name_prefix       = "deployctrl-platform"
bucket_name       = "deployctrl-platform-84a4e40d"
