# Generated by DeployCtrl
# Request ID  : 69c73bdc98094ff84b83af7f
# Template    : S3 Bucket
# Team        : Product A
# Requested by: Alice Developer
# Region      : eu-west-1

storage_class     = "STANDARD_IA"
estimated_size_gb = 500
versioning        = "Enabled"
encryption        = "AES256"
access_control    = "private"
lifecycle_days    = 90
region            = "eu-west-1"
name_prefix       = "deployctrl-product-a"
bucket_name       = "deployctrl-product-a-4b83af7f"
