# Generated by DeployCtrl
# Request ID  : 69fa7d8748ebe078491aa643
# Template    : S3 Bucket
# Team        : Platform
# Requested by: Admin User
# Region      : us-east-1

storage_class     = "STANDARD"
estimated_size_gb = 10
versioning        = "Suspended"
encryption        = "AES256"
access_control    = "private"
lifecycle_days    = 0
region            = "us-east-1"
name_prefix       = "deployctrl-platform-req-0003"
bucket_name       = "deployctrl-platform-491aa643"
