# Generated by DeployCtrl
# Request ID  : 69d46646f59788bfc6af300c
# Template    : EC2 Instance
# Team        : Platform
# Requested by: Admin User
# Region      : us-east-1

instance_type = "t3.small"
disk_type     = "gp3"
disk_size_gb  = 20
os            = "amazon-linux-2"
region        = "us-east-1"
name_prefix   = "deployctrl-platform"
