# Generated by DeployCtrl
# Request ID  : 69d4726dd13c24614b4304b8
# Template    : S3 Bucket
# Team        : Governance
# Requested by: Bob Architect
# Region      : us-east-1

storage_class     = "STANDARD"
estimated_size_gb = 10
versioning        = "Enabled"
encryption        = "AES256"
access_control    = "private"
lifecycle_days    = 0
region            = "us-east-1"
name_prefix       = "deployctrl-governance"
bucket_name       = "deployctrl-governance-4b4304b8"
