# Generated by DeployCtrl
# Request ID  : 69d6f5e65ec48ae184a4e3ef
# Template    : EC2 Instance
# Team        : Product A
# Requested by: Alice Developer
# Region      : us-east-1

instance_type  = "t3.small"
disk_type      = "gp3"
disk_size_gb   = "200"
os             = "amazon-linux-2"
inbound_ports  = ["22", "80", "443"]
outbound_ports = ["all"]
region         = "us-east-1"
name_prefix    = "deployctrl-product-a"
