# Auto-generated by CloudGov for Request REQ-8860
# Team: Product A
# Region: us-east-1
# Generated at: 2026-03-17T07:18:34.192Z

provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      Environment = "Development"
      Team        = "Product A"
      ManagedBy   = "CloudGov"
      RequestId   = "REQ-8860"
    }
  }
}


resource "aws_s3_bucket" "secure_bucket" {
  bucket_prefix = "cloudgov-secure-REQ-8860-"
}

resource "aws_s3_bucket_versioning" "versioning" {
  bucket = aws_s3_bucket.secure_bucket.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "encryption" {
  bucket = aws_s3_bucket.secure_bucket.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "block_public" {
  bucket = aws_s3_bucket.secure_bucket.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
