# Auto-generated by CloudGov for Request REQ-8601
# Team: Product A
# Region: us-east-1
# Generated at: 2026-03-13T23:41:09.844Z

provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      Environment = "Development"
      Team        = "Product A"
      ManagedBy   = "CloudGov"
      RequestId   = "REQ-8601"
    }
  }
}


resource "aws_elasticache_cluster" "redis" {
  cluster_id           = "redis-REQ-8601"
  engine               = "redis"
  node_type            = "cache.t3.small"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis7"
  engine_version       = "7.0"
  port                 = 6379
}
