# Auto-generated by CloudGov for Request REQ-3109
# Team: Product A
# Region: us-east-1
# Generated at: 2026-03-14T04:14:24.699Z

provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      Environment = "Development"
      Team        = "Product A"
      ManagedBy   = "CloudGov"
      RequestId   = "REQ-3109"
    }
  }
}


module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 19.0"

  cluster_name    = "eks-dev-REQ-3109"
  cluster_version = "1.27"

  cluster_endpoint_public_access = true

  vpc_id     = "vpc-12345678" # Placeholder
  subnet_ids = ["subnet-12345678", "subnet-87654321"]

  eks_managed_node_groups = {
    dev = {
      min_size     = 1
      max_size     = 2
      desired_size = 2

      instance_types = ["t3.medium"]
      capacity_type  = "SPOT"
    }
  }
}
