# Generated by DeployCtrl
# Request ID  : 69c7be573fe11920d6f8cfb6
# Template    : S3 Bucket
# Team        : Product A
# Requested by: Alice Developer
# Region      : us-east-1

storage_class     = "STANDARD"
estimated_size_gb = 10
versioning        = "Enabled"
encryption        = "AES256"
access_control    = "private"
lifecycle_days    = 0
region            = "us-east-1"
name_prefix       = "deployctrl-product-a"
bucket_name       = "deployctrl-product-a-d6f8cfb6"
